### ISSUE TITLE
Switch to CSS class, not id

### ISSUE THREAD

**Issue by Quix0r** [dgoooo/css3-snow-animation#1]
Being forced to have an id (which must be unique in whole DOM document) is a bad idea as people have then to add a div container to their code. I would recommend switching to a class, the change is marginal yet much better for other people:

````
.snow {
[...]
}
````

... and:

````
<div class="snow">
</div>
````

Then people can much easier add snow their website by just adding `class="snow"` (or expand existing CSS classes with `snow`) to their templates/HTML documents/whatever they might use.

**Comment by dgoooo** [comment]
True, and it's also a good idea to not link directly to the images, I just want the code to work for the most amount of people possible. But will probably end up being the same mistake I initially fixed. Will add notes to the README. Thanks.

**Comment by Quix0r** [comment]
You are welcome.
